# site properties and page defaults
title: Systems Aging Lab
subtitle: Weslake Univeristy, Center for Interdisciplinary Studies 
description: We combine mathematical modelling, data analysis and quantitative experiments to uncover principles of aging, cellular stress response and tissue homeostasis. 
baseurl: "/yifanlab"  # For user sites (username.github.io)
url: "https://yifanlab.org"  # Replace with your domain
footer: images/background.jpg
proofer: false

# site social media and other links
links:
  email: yangyifan at westlake.edu.cn
  orcid: 0000-0001-6697-0198
  google-scholar: 
  github: y1fanyang
  twitter: y1fanyang
  youtube: 

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
